#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mpi4py
Version  : 3.1.2
Release  : 37
URL      : https://github.com/mpi4py/mpi4py/releases/download/3.1.2/mpi4py-3.1.2.tar.gz
Source0  : https://github.com/mpi4py/mpi4py/releases/download/3.1.2/mpi4py-3.1.2.tar.gz
Summary  : Python bindings for MPI
Group    : Development/Tools
License  : BSD-2-Clause
Requires: mpi4py-license = %{version}-%{release}
Requires: mpi4py-python = %{version}-%{release}
Requires: mpi4py-python3 = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-distutils3
BuildRequires : openmpi-dev
BuildRequires : setuptools
BuildRequires : wheel

%description
==============
MPI for Python
==============
.. image::  https://github.com/mpi4py/mpi4py/workflows/ci/badge.svg?branch=master
:target: https://github.com/mpi4py/mpi4py/actions/
.. image::  https://readthedocs.org/projects/mpi4py/badge/?version=latest
:target: https://mpi4py.readthedocs.io/en/latest/
.. image::  https://dev.azure.com/mpi4py/mpi4py/_apis/build/status/ci?branchName=master
:target: https://dev.azure.com/mpi4py/mpi4py/_build
.. image::  https://ci.appveyor.com/api/projects/status/whh5xovp217h0f7n?svg=true
:target: https://ci.appveyor.com/project/mpi4py/mpi4py
.. image::  https://circleci.com/gh/mpi4py/mpi4py.svg?style=shield
:target: https://circleci.com/gh/mpi4py/mpi4py
.. image::  https://app.travis-ci.com/mpi4py/mpi4py.svg?branch=master
:target: https://app.travis-ci.com/mpi4py/mpi4py
.. image::  https://codecov.io/gh/mpi4py/mpi4py/branch/master/graph/badge.svg
:target: https://codecov.io/gh/mpi4py/mpi4py
.. image::  https://scan.coverity.com/projects/mpi4py-mpi4py/badge.svg
:target: https://scan.coverity.com/projects/mpi4py-mpi4py

%package dev
Summary: dev components for the mpi4py package.
Group: Development
Provides: mpi4py-devel = %{version}-%{release}
Requires: mpi4py = %{version}-%{release}

%description dev
dev components for the mpi4py package.


%package doc
Summary: doc components for the mpi4py package.
Group: Documentation

%description doc
doc components for the mpi4py package.


%package license
Summary: license components for the mpi4py package.
Group: Default

%description license
license components for the mpi4py package.


%package python
Summary: python components for the mpi4py package.
Group: Default
Requires: mpi4py-python3 = %{version}-%{release}

%description python
python components for the mpi4py package.


%package python3
Summary: python3 components for the mpi4py package.
Group: Default
Requires: python3-core
Provides: pypi(mpi4py)

%description python3
python3 components for the mpi4py package.


%prep
%setup -q -n mpi4py-3.1.2
cd %{_builddir}/mpi4py-3.1.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1637090770
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/mpi4py
cp %{_builddir}/mpi4py-3.1.2/LICENSE.rst %{buildroot}/usr/share/package-licenses/mpi4py/b3a503c1c32c5015e6c9fd9ff6f97a93c611aaeb
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
## install_append content
mkdir -p %{buildroot}/usr/share/doc/mpi4py
cp -r demo %{buildroot}/usr/share/doc/mpi4py
cp -r docs %{buildroot}/usr/share/doc/mpi4py
## install_append end

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/lib/python3.10/site-packages/mpi4py/include/mpi4py/mpi4py.MPI.h
/usr/lib/python3.10/site-packages/mpi4py/include/mpi4py/mpi4py.MPI_api.h
/usr/lib/python3.10/site-packages/mpi4py/include/mpi4py/mpi4py.h

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/mpi4py/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mpi4py/b3a503c1c32c5015e6c9fd9ff6f97a93c611aaeb

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
