#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mpi4py
Version  : 3.0.3
Release  : 35
URL      : https://bitbucket.org/mpi4py/mpi4py/downloads/mpi4py-3.0.3.tar.gz
Source0  : https://bitbucket.org/mpi4py/mpi4py/downloads/mpi4py-3.0.3.tar.gz
Summary  : Python bindings for MPI
Group    : Development/Tools
License  : BSD-2-Clause
Requires: mpi4py-license = %{version}-%{release}
Requires: mpi4py-python = %{version}-%{release}
Requires: mpi4py-python3 = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-distutils3
BuildRequires : openmpi-dev
BuildRequires : python3-dev

%description
==============
        
        This package provides Python bindings for the **Message Passing
        Interface** (MPI_) standard. It is implemented on top of the MPI-1/2/3
        specification and exposes an API which grounds on the standard MPI-2
        C++ bindings.

%package dev
Summary: dev components for the mpi4py package.
Group: Development
Provides: mpi4py-devel = %{version}-%{release}
Requires: mpi4py = %{version}-%{release}

%description dev
dev components for the mpi4py package.


%package doc
Summary: doc components for the mpi4py package.
Group: Documentation

%description doc
doc components for the mpi4py package.


%package license
Summary: license components for the mpi4py package.
Group: Default

%description license
license components for the mpi4py package.


%package python
Summary: python components for the mpi4py package.
Group: Default
Requires: mpi4py-python3 = %{version}-%{release}

%description python
python components for the mpi4py package.


%package python3
Summary: python3 components for the mpi4py package.
Group: Default
Requires: python3-core
Provides: pypi(mpi4py)

%description python3
python3 components for the mpi4py package.


%prep
%setup -q -n mpi4py-3.0.3
cd %{_builddir}/mpi4py-3.0.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1607985844
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/mpi4py
cp %{_builddir}/mpi4py-3.0.3/LICENSE.rst %{buildroot}/usr/share/package-licenses/mpi4py/21edae501e74d2238beb8de11f7cc57c76ec35d8
cp %{_builddir}/mpi4py-3.0.3/docs/LICENSE.html %{buildroot}/usr/share/package-licenses/mpi4py/9a87cc8595ac41877df310100498725e846c2791
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
## install_append content
mkdir -p %{buildroot}/usr/share/doc/mpi4py
cp -r demo %{buildroot}/usr/share/doc/mpi4py
cp -r docs %{buildroot}/usr/share/doc/mpi4py
## install_append end

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/lib/python3.9/site-packages/mpi4py/include/mpi4py/mpi4py.MPI.h
/usr/lib/python3.9/site-packages/mpi4py/include/mpi4py/mpi4py.MPI_api.h
/usr/lib/python3.9/site-packages/mpi4py/include/mpi4py/mpi4py.h

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/mpi4py/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mpi4py/21edae501e74d2238beb8de11f7cc57c76ec35d8
/usr/share/package-licenses/mpi4py/9a87cc8595ac41877df310100498725e846c2791

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
